spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kulture
    username: root
    password: zxc74100
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug

